unless Poolie.exists?
#  Poolie.create(:name => 'Chris Wise', :team_name => 'Wise Asses', :draft_order => 1)
#  Poolie.create(:name => 'Paul Wong', :team_name => 'Stupid Dawgs', :draft_order => 2)
#  Poolie.create(:name => 'Mike Peralta', :team_name => 'Mikey Peraltas', :draft_order => 3)
#  Poolie.create(:name => 'Craig Kavanagh', :team_name => 'Craigbots', :draft_order => 4)
#  Poolie.create(:name => 'Dan Pascoli', :team_name => 'Camp Holdouts', :draft_order => 5)
#  Poolie.create(:name => 'Dave Bisson', :team_name => 'Da Wanabe Ladies Man', :draft_order => 6)
#  Poolie.create(:name => 'Rainy Jodoin', :team_name => 'X-Rated', :draft_order => 7)
#  Poolie.create(:name => 'Jesse Fleming', :team_name => 'Big Poppa', :draft_order => 8)
#  Poolie.create(:name => 'Louis-Martin Parent', :team_name => 'Crackton United', :draft_order => 9)
#  Poolie.create(:name => 'Chris Maloney', :team_name => 'Fancy Lions', :draft_order => 10)
#  Poolie.create(:name => 'Marc Pascoli', :team_name => 'Stallions', :draft_order => 11)
#  Poolie.create(:name => 'Fred Cooke', :team_name => 'The Godfather', :draft_order => 12)
end

unless Poolie.exists?
  Poolie.create(:name => 'Craig Kavanagh', :team_name => 'Craigbots', :draft_order => 0)
  Poolie.create(:name => 'Jaeme Gloyn', :team_name => 'Jaeme _ Gloyn', :draft_order => 0)
  Poolie.create(:name => 'Jeremy Lendvay', :team_name => 'Officer McClusky', :draft_order => 0)
  Poolie.create(:name => 'Scott Drover', :team_name => 'Drover''s Drivers', :draft_order => 0)
  Poolie.create(:name => 'Darcy Ferron', :team_name => 'Chez Paree 69ers', :draft_order => 0)
  Poolie.create(:name => 'Jared Rosenfeld', :team_name => 'Marino''s Man Food', :draft_order => 0)
  Poolie.create(:name => 'Joey Mousseau', :team_name => 'LongCocks', :draft_order => 0)
  Poolie.create(:name => 'Wes Blight', :team_name => 'Fleet Feet', :draft_order => 0)
  Poolie.create(:name => 'Brad Wood', :team_name => 'Sunday Morning Wood', :draft_order => 0)
  Poolie.create(:name => 'Travis Gloyn', :team_name => 'The Hitmen Humpers', :draft_order => 0)
  Poolie.create(:name => 'Andrew Gowing', :team_name => 'The Gowningnators', :draft_order => 0)
  Poolie.create(:name => 'Josh Moore', :team_name => 'josh', :draft_order => 0)
end

unless Player.exists?
  Player.create(:name => ' Aaron Rodgers', :team => 'GB',:position => 'QB')
  Player.create(:name => ' Drew Brees', :team => 'NO',:position => 'QB')
  Player.create(:name => ' Tom Brady', :team => 'NE',:position => 'QB')
  Player.create(:name => ' Peyton Manning', :team => 'IND',:position => 'QB')
  Player.create(:name => ' Tony Romo', :team => 'DAL',:position => 'QB')
  Player.create(:name => ' Matt Schaub', :team => 'HOU',:position => 'QB')
  Player.create(:name => ' Jay Cutler', :team => 'CHI',:position => 'QB')
  Player.create(:name => ' Kevin Kolb ', :team => 'PHI',:position => 'QB')
  Player.create(:name => ' Eli Manning', :team => 'NYG',:position => 'QB')
  Player.create(:name => ' David Garrard', :team => 'JAC',:position => 'QB')
  Player.create(:name => ' Philip Rivers', :team => 'SD',:position => 'QB')
  Player.create(:name => ' Joe Flacco', :team => 'BAL',:position => 'QB')
  Player.create(:name => ' Brett Favre  ', :team => 'MIN',:position => 'QB')
  Player.create(:name => ' Matt Ryan', :team => 'ATL',:position => 'QB')
  Player.create(:name => ' Carson Palmer', :team => 'CIN',:position => 'QB')
  Player.create(:name => ' Donovan McNabb', :team => 'WAS',:position => 'QB')
  Player.create(:name => ' Josh Freeman', :team => 'TB',:position => 'QB')
  Player.create(:name => ' Matt Cassel', :team => 'KC',:position => 'QB')
  Player.create(:name => ' Matthew Stafford', :team => 'DET',:position => 'QB')
  Player.create(:name => ' Alex Smith', :team => 'SF',:position => 'QB')
  Player.create(:name => ' Vince Young', :team => 'TEN',:position => 'QB')
  Player.create(:name => ' Jason Campbell', :team => 'OAK',:position => 'QB')
  Player.create(:name => ' Chad Henne', :team => 'MIA',:position => 'QB')
  Player.create(:name => ' Kyle Orton', :team => 'DEN',:position => 'QB')
  Player.create(:name => ' Mark Sanchez', :team => 'NYJ',:position => 'QB')
  Player.create(:name => ' Ben Roethlisberger  ', :team => 'PIT',:position => 'QB')
  Player.create(:name => ' Matt Moore', :team => 'CAR',:position => 'QB')
  Player.create(:name => ' Matt Hasselbeck', :team => 'SEA',:position => 'QB')
  Player.create(:name => ' Derek Anderson', :team => 'ARI',:position => 'QB')
  Player.create(:name => ' Sam Bradford', :team => 'STL',:position => 'QB')
  Player.create(:name => ' Jake Delhomme', :team => 'CLE',:position => 'QB')
  Player.create(:name => ' Trent Edwards', :team => 'BUF',:position => 'QB')
  Player.create(:name => ' Brian Brohm', :team => 'BUF',:position => 'QB')
  Player.create(:name => ' Charlie Whitehurst', :team => 'SEA',:position => 'QB')
  Player.create(:name => ' Seneca Wallace', :team => 'CLE',:position => 'QB')
  Player.create(:name => ' Dennis Dixon', :team => 'PIT',:position => 'QB')
  Player.create(:name => ' Matt Leinart  ', :team => 'ARI',:position => 'QB')
  Player.create(:name => ' A.J. Feeley', :team => 'STL',:position => 'QB')
  Player.create(:name => ' Michael Vick', :team => 'PHI',:position => 'QB')
  Player.create(:name => ' Shaun Hill', :team => 'DET',:position => 'QB')
  Player.create(:name => ' Jimmy Clausen', :team => 'CAR',:position => 'QB')
  Player.create(:name => ' Charlie Batch', :team => 'PIT',:position => 'QB')
  Player.create(:name => ' Kerry Collins', :team => 'TEN',:position => 'QB')
  Player.create(:name => ' Josh Johnson', :team => 'TB',:position => 'QB')
  Player.create(:name => ' David Carr', :team => 'SF',:position => 'QB')
  Player.create(:name => ' Rex Grossman', :team => 'WAS',:position => 'QB')
  Player.create(:name => ' Sage Rosenfels', :team => 'MIN',:position => 'QB')
  Player.create(:name => ' Bruce Gradkowski', :team => 'OAK',:position => 'QB')
  Player.create(:name => ' Kellen Clemens', :team => 'NYJ',:position => 'QB')
  Player.create(:name => ' Tyler Thigpen', :team => 'MIA',:position => 'QB')
  Player.create(:name => ' Adrian Peterson', :team => 'MIN',:position => 'RB')
  Player.create(:name => ' Chris Johnson', :team => 'TEN',:position => 'RB')
  Player.create(:name => ' Maurice Jones-Drew', :team => 'JAC',:position => 'RB')
  Player.create(:name => ' Ray Rice', :team => 'BAL',:position => 'RB')
  Player.create(:name => ' Frank Gore', :team => 'SF',:position => 'RB')
  Player.create(:name => ' Ryan Mathews', :team => 'SD',:position => 'RB')
  Player.create(:name => ' Rashard Mendenhall', :team => 'PIT',:position => 'RB')
  Player.create(:name => ' Steven Jackson', :team => 'STL',:position => 'RB')
  Player.create(:name => ' Michael Turner', :team => 'ATL',:position => 'RB')
  Player.create(:name => ' DeAngelo Williams', :team => 'CAR',:position => 'RB')
  Player.create(:name => ' Shonn Greene', :team => 'NYJ',:position => 'RB')
  Player.create(:name => ' Ryan Grant', :team => 'GB',:position => 'RB')
  Player.create(:name => ' Jamaal Charles  ', :team => 'KC',:position => 'RB')
  Player.create(:name => ' Cedric Benson', :team => 'CIN',:position => 'RB')
  Player.create(:name => ' Pierre Thomas', :team => 'NO',:position => 'RB')
  Player.create(:name => ' Ahmad Bradshaw', :team => 'NYG',:position => 'RB')
  Player.create(:name => ' Clinton Portis', :team => 'WAS',:position => 'RB')
  Player.create(:name => ' Matt Forte', :team => 'CHI',:position => 'RB')
  Player.create(:name => ' Jahvid Best ', :team => 'DET',:position => 'RB')
  Player.create(:name => ' Chris Wells', :team => 'ARI',:position => 'RB')
  Player.create(:name => ' Cadillac Williams', :team => 'TB',:position => 'RB')
  Player.create(:name => ' LeSean McCoy', :team => 'PHI',:position => 'RB')
  Player.create(:name => ' Knowshon Moreno  ', :team => 'DEN',:position => 'RB')
  Player.create(:name => ' Joseph Addai', :team => 'IND',:position => 'RB')
  Player.create(:name => ' Justin Forsett ', :team => 'SEA',:position => 'RB')
  Player.create(:name => ' Ricky Williams', :team => 'MIA',:position => 'RB')
  Player.create(:name => ' Felix Jones ', :team => 'DAL',:position => 'RB')
  Player.create(:name => ' Jonathan Stewart', :team => 'CAR',:position => 'RB')
  Player.create(:name => ' C.J. Spiller', :team => 'BUF',:position => 'RB')
  Player.create(:name => ' Arian Foster ', :team => 'HOU',:position => 'RB')
  Player.create(:name => ' Tim Hightower', :team => 'ARI',:position => 'RB')
  Player.create(:name => ' Brandon Jacobs', :team => 'NYG',:position => 'RB')
  Player.create(:name => ' Marion Barber', :team => 'DAL',:position => 'RB')
  Player.create(:name => ' Reggie Bush', :team => 'NO',:position => 'RB')
  Player.create(:name => ' LaDainian Tomlinson', :team => 'NYJ',:position => 'RB')
  Player.create(:name => ' Jerome Harrison ', :team => 'CLE',:position => 'RB')
  Player.create(:name => ' Laurence Maroney', :team => 'NE',:position => 'RB')
  Player.create(:name => ' Ronnie Brown  ', :team => 'MIA',:position => 'RB')
  Player.create(:name => ' Michael Bush', :team => 'OAK',:position => 'RB')
  Player.create(:name => ' Donald Brown', :team => 'IND',:position => 'RB')
  Player.create(:name => ' Fred Jackson', :team => 'BUF',:position => 'RB')
  Player.create(:name => ' Darren McFadden', :team => 'OAK',:position => 'RB')
  Player.create(:name => ' Steve Slaton  ', :team => 'HOU',:position => 'RB')
  Player.create(:name => ' Correll Buckhalter', :team => 'DEN',:position => 'RB')
  Player.create(:name => ' Willis McGahee', :team => 'BAL',:position => 'RB')
  Player.create(:name => ' Darren Sproles', :team => 'SD',:position => 'RB')
  Player.create(:name => ' Thomas Jones', :team => 'KC',:position => 'RB')
  Player.create(:name => ' Kevin Faulk', :team => 'NE',:position => 'RB')
  Player.create(:name => ' Toby Gerhart', :team => 'MIN',:position => 'RB')
  Player.create(:name => ' Jerious Norwood', :team => 'ATL',:position => 'RB')
  Player.create(:name => ' Andre Johnson', :team => 'HOU',:position => 'WR')
  Player.create(:name => ' Randy Moss', :team => 'NE',:position => 'WR')
  Player.create(:name => ' Miles Austin', :team => 'DAL',:position => 'WR')
  Player.create(:name => ' Reggie Wayne', :team => 'IND',:position => 'WR')
  Player.create(:name => ' Roddy White', :team => 'ATL',:position => 'WR')
  Player.create(:name => ' Larry Fitzgerald', :team => 'ARI',:position => 'WR')
  Player.create(:name => ' DeSean Jackson', :team => 'PHI',:position => 'WR')
  Player.create(:name => ' Calvin Johnson', :team => 'DET',:position => 'WR')
  Player.create(:name => ' Greg Jennings', :team => 'GB',:position => 'WR')
  Player.create(:name => ' Brandon Marshall', :team => 'MIA',:position => 'WR')
  Player.create(:name => ' Marques Colston', :team => 'NO',:position => 'WR')
  Player.create(:name => ' Steve Smith  ', :team => 'CAR',:position => 'WR')
  Player.create(:name => ' Chad Ochocinco', :team => 'CIN',:position => 'WR')
  Player.create(:name => ' Santana Moss ', :team => 'WAS',:position => 'WR')
  Player.create(:name => ' Mike Sims-Walker', :team => 'JAC',:position => 'WR')
  Player.create(:name => ' Hines Ward', :team => 'PIT',:position => 'WR')
  Player.create(:name => ' Steve Smith', :team => 'NYG',:position => 'WR')
  Player.create(:name => ' Anquan Boldin', :team => 'BAL',:position => 'WR')
  Player.create(:name => ' T.J. Houshmandzadeh', :team => 'SEA',:position => 'WR')
  Player.create(:name => ' Hakeem Nicks', :team => 'NYG',:position => 'WR')
  Player.create(:name => ' Michael Crabtree', :team => 'SF',:position => 'WR')
  Player.create(:name => ' Dwayne Bowe', :team => 'KC',:position => 'WR')
  Player.create(:name => ' Malcom Floyd ', :team => 'SD',:position => 'WR')
  Player.create(:name => ' Lee Evans', :team => 'BUF',:position => 'WR')
  Player.create(:name => ' Terrell Owens', :team => 'CIN',:position => 'WR')
  Player.create(:name => ' Percy Harvin  ', :team => 'MIN',:position => 'WR')
  Player.create(:name => ' Jabar Gaffney', :team => 'DEN',:position => 'WR')
  Player.create(:name => ' Mike Wallace ', :team => 'PIT',:position => 'WR')
  Player.create(:name => ' Donald Driver', :team => 'GB',:position => 'WR')
  Player.create(:name => ' Johnny Knox', :team => 'CHI',:position => 'WR')
  Player.create(:name => ' Derrick Mason', :team => 'BAL',:position => 'WR')
  Player.create(:name => ' Wes Welker  ', :team => 'NE',:position => 'WR')
  Player.create(:name => ' Robert Meachem', :team => 'NO',:position => 'WR')
  Player.create(:name => ' Pierre Garcon', :team => 'IND',:position => 'WR')
  Player.create(:name => ' Devin Hester', :team => 'CHI',:position => 'WR')
  Player.create(:name => ' Jeremy Maclin', :team => 'PHI',:position => 'WR')
  Player.create(:name => ' Bernard Berrian ', :team => 'MIN',:position => 'WR')
  Player.create(:name => ' Mohamed Massaquoi', :team => 'CLE',:position => 'WR')
  Player.create(:name => ' Mike Williams', :team => 'TB',:position => 'WR')
  Player.create(:name => ' Nate Washington', :team => 'TEN',:position => 'WR')
  Player.create(:name => ' Dez Bryant ', :team => 'DAL',:position => 'WR')
  Player.create(:name => ' Laurent Robinson', :team => 'STL',:position => 'WR')
  Player.create(:name => ' Braylon Edwards', :team => 'NYJ',:position => 'WR')
  Player.create(:name => ' Kenny Britt', :team => 'TEN',:position => 'WR')
  Player.create(:name => ' Louis Murphy', :team => 'OAK',:position => 'WR')
  Player.create(:name => ' Eddie Royal', :team => 'DEN',:position => 'WR')
  Player.create(:name => ' Steve Breaston', :team => 'ARI',:position => 'WR')
  Player.create(:name => ' Jerricho Cotchery', :team => 'NYJ',:position => 'WR')
  Player.create(:name => ' Mike Thomas', :team => 'JAC',:position => 'WR')
  Player.create(:name => ' Brian Hartline', :team => 'MIA',:position => 'WR')
  Player.create(:name => ' Jacoby Jones', :team => 'HOU',:position => 'WR')
  Player.create(:name => ' Vincent Jackson', :team => 'SD',:position => 'WR')
  Player.create(:name => ' Chris Chambers', :team => 'KC',:position => 'WR')
  Player.create(:name => ' Josh Morgan', :team => 'SF',:position => 'WR')
  Player.create(:name => ' Devin Aromashodu', :team => 'CHI',:position => 'WR')
  Player.create(:name => ' Lance Moore', :team => 'NO',:position => 'WR')
  Player.create(:name => ' Nate Burleson', :team => 'DET',:position => 'WR')
  Player.create(:name => ' Julian Edelman ', :team => 'NE',:position => 'WR')
  Player.create(:name => ' Darrius Heyward-Bey', :team => 'OAK',:position => 'WR')
  Player.create(:name => ' Santonio Holmes  ', :team => 'NYJ',:position => 'WR')
  Player.create(:name => ' Early Doucet', :team => 'ARI',:position => 'WR')
  Player.create(:name => ' Dexter McCluster', :team => 'KC',:position => 'WR')
  Player.create(:name => ' James Jones', :team => 'GB',:position => 'WR')
  Player.create(:name => ' Mario Manningham', :team => 'NYG',:position => 'WR')
  Player.create(:name => ' Steve Johnson', :team => 'BUF',:position => 'WR')
  Player.create(:name => ' Danny Amendola', :team => 'STL',:position => 'WR')
  Player.create(:name => ' Anthony Gonzalez', :team => 'IND',:position => 'WR')
  Player.create(:name => ' Brandon LaFell', :team => 'CAR',:position => 'WR')
  Player.create(:name => ' Legedu Naanee', :team => 'SD',:position => 'WR')
  Player.create(:name => ' Kevin Walter', :team => 'HOU',:position => 'WR')
  Player.create(:name => ' Josh Cribbs', :team => 'CLE',:position => 'WR')
  Player.create(:name => ' Devery Henderson', :team => 'NO',:position => 'WR')
  Player.create(:name => ' Roy Williams  ', :team => 'DAL',:position => 'WR')
  Player.create(:name => ' Brandon Tate', :team => 'NE',:position => 'WR')
  Player.create(:name => ' Michael Jenkins', :team => 'ATL',:position => 'WR')
  Player.create(:name => ' Golden Tate', :team => 'SEA',:position => 'WR')
  Player.create(:name => ' Brian Robiskie', :team => 'CLE',:position => 'WR')
  Player.create(:name => ' Harry Douglas', :team => 'ATL',:position => 'WR')
  Player.create(:name => ' Davone Bess', :team => 'MIA',:position => 'WR')
  Player.create(:name => ' Demaryius Thomas', :team => 'DEN',:position => 'WR')
  Player.create(:name => ' Dwayne Jarrett', :team => 'CAR',:position => 'WR')
  Player.create(:name => ' Devin Thomas', :team => 'WAS',:position => 'WR')
  Player.create(:name => ' Jordan Shipley', :team => 'CIN',:position => 'WR')
  Player.create(:name => ' Chaz Schilens', :team => 'OAK',:position => 'WR')
  Player.create(:name => ' Joey Galloway', :team => 'WAS',:position => 'WR')
  Player.create(:name => ' Mike Williams', :team => 'SEA',:position => 'WR')
  Player.create(:name => ' Jason Avant', :team => 'PHI',:position => 'WR')
  Player.create(:name => ' Sidney Rice', :team => 'MIN',:position => 'WR')
  Player.create(:name => ' Sammie Stroughter', :team => 'TB',:position => 'WR')
  Player.create(:name => ' James Hardy', :team => 'BUF',:position => 'WR')
  Player.create(:name => ' Justin Gage', :team => 'TEN',:position => 'WR')
  Player.create(:name => ' Bryant Johnson', :team => 'DET',:position => 'WR')
  Player.create(:name => ' Austin Collie', :team => 'IND',:position => 'WR')
  Player.create(:name => ' Keenan Burton', :team => 'STL',:position => 'WR')
  Player.create(:name => ' Arrelious Benn', :team => 'TB',:position => 'WR')
  Player.create(:name => ' Mark Clayton', :team => 'BAL',:position => 'WR')
  Player.create(:name => ' Johnnie Lee Higgins', :team => 'OAK',:position => 'WR')
  Player.create(:name => ' Jarett Dillard', :team => 'JAC',:position => 'WR')
  Player.create(:name => ' Earl Bennett', :team => 'CHI',:position => 'WR')
  Player.create(:name => ' Jordy Nelson', :team => 'GB',:position => 'WR')
  Player.create(:name => ' Antonio Gates', :team => 'SD',:position => 'TE')
  Player.create(:name => ' Jermichael Finley ', :team => 'GB',:position => 'TE')
  Player.create(:name => ' Vernon Davis', :team => 'SF',:position => 'TE')
  Player.create(:name => ' Dallas Clark', :team => 'IND',:position => 'TE')
  Player.create(:name => ' Jason Witten', :team => 'DAL',:position => 'TE')
  Player.create(:name => ' Tony Gonzalez', :team => 'ATL',:position => 'TE')
  Player.create(:name => ' Brent Celek ', :team => 'PHI',:position => 'TE')
  Player.create(:name => ' Kellen Winslow', :team => 'TB',:position => 'TE')
  Player.create(:name => ' Zach Miller ', :team => 'OAK',:position => 'TE')
  Player.create(:name => ' John Carlson', :team => 'SEA',:position => 'TE')
  Player.create(:name => ' Heath Miller', :team => 'PIT',:position => 'TE')
  Player.create(:name => ' Visanthe Shiancoe', :team => 'MIN',:position => 'TE')
  Player.create(:name => ' Chris Cooley  ', :team => 'WAS',:position => 'TE')
  Player.create(:name => ' Owen Daniels  ', :team => 'HOU',:position => 'TE')
  Player.create(:name => ' Greg Olsen', :team => 'CHI',:position => 'TE')
  Player.create(:name => ' Jeremy Shockey', :team => 'NO',:position => 'TE')
  Player.create(:name => ' Dustin Keller', :team => 'NYJ',:position => 'TE')
  Player.create(:name => ' Todd Heap', :team => 'BAL',:position => 'TE')
  Player.create(:name => ' Marcedes Lewis', :team => 'JAC',:position => 'TE')
  Player.create(:name => ' Kevin Boss', :team => 'NYG',:position => 'TE')
  Player.create(:name => ' Bo Scaife', :team => 'TEN',:position => 'TE')
  Player.create(:name => ' Fred Davis ', :team => 'WAS',:position => 'TE')
  Player.create(:name => ' Anthony Fasano', :team => 'MIA',:position => 'TE')
  Player.create(:name => ' Ben Watson', :team => 'CLE',:position => 'TE')
  Player.create(:name => ' Tony Scheffler', :team => 'DET',:position => 'TE')
  Player.create(:name => ' Daniel Graham', :team => 'DEN',:position => 'TE')
  Player.create(:name => ' Dante Rosario', :team => 'CAR',:position => 'TE')
  Player.create(:name => ' Daniel Fells', :team => 'STL',:position => 'TE')
  Player.create(:name => ' Jermaine Gresham', :team => 'CIN',:position => 'TE')
  Player.create(:name => ' Aaron Hernandez', :team => 'NE',:position => 'TE')
  Player.create(:name => ' David Thomas', :team => 'NO',:position => 'TE')
  Player.create(:name => ' Leonard Pope', :team => 'KC',:position => 'TE')
  Player.create(:name => ' Jared Cook', :team => 'TEN',:position => 'TE')
  Player.create(:name => ' Gary Barnidge', :team => 'CAR',:position => 'TE')
  Player.create(:name => ' Evan Moore', :team => 'CLE',:position => 'TE')
  Player.create(:name => ' Donald Lee', :team => 'GB',:position => 'TE')
  Player.create(:name => ' Brandon Pettigrew', :team => 'DET',:position => 'TE')
  Player.create(:name => ' Jerramy Stevens', :team => 'TB',:position => 'TE')
  Player.create(:name => ' Alge Crumpler', :team => 'NE',:position => 'TE')
  Player.create(:name => ' Shawn Nelson', :team => 'BUF',:position => 'TE')
  Player.create(:name => ' Tony Moeaki', :team => 'KC',:position => 'TE')
  Player.create(:name => ' Billy Bajema', :team => 'STL',:position => 'TE')
  Player.create(:name => ' Delanie Walker', :team => 'SF',:position => 'TE')
  Player.create(:name => ' Zach Miller', :team => 'JAC',:position => 'TE')
  Player.create(:name => ' Ben Patrick', :team => 'ARI',:position => 'TE')
  Player.create(:name => ' Derek Schouman', :team => 'BUF',:position => 'TE')
  Player.create(:name => ' James Casey ', :team => 'HOU',:position => 'TE')
  Player.create(:name => ' Desmond Clark', :team => 'CHI',:position => 'TE')
  Player.create(:name => ' Jeff King', :team => 'CAR',:position => 'TE')
  Player.create(:name => ' Martellus Bennett', :team => 'DAL',:position => 'TE')
  Player.create(:name => ' Stephen Gostkowski', :team => 'NE',:position => 'K')
  Player.create(:name => ' Garrett Hartley', :team => 'NO',:position => 'K')
  Player.create(:name => ' Nate Kaeding', :team => 'SD',:position => 'K')
  Player.create(:name => ' Ryan Longwell', :team => 'MIN',:position => 'K')
  Player.create(:name => ' Mason Crosby', :team => 'GB',:position => 'K')
  Player.create(:name => ' David Akers', :team => 'PHI',:position => 'K')
  Player.create(:name => ' Neil Rackers ', :team => 'HOU',:position => 'K')
  Player.create(:name => ' Lawrence Tynes', :team => 'NYG',:position => 'K')
  Player.create(:name => ' Rob Bironas', :team => 'TEN',:position => 'K')
  Player.create(:name => ' Jeff Reed', :team => 'PIT',:position => 'K')
  Player.create(:name => ' David Buehler', :team => 'DAL',:position => 'K')
  Player.create(:name => ' Matt Prater', :team => 'DEN',:position => 'K')
  Player.create(:name => ' Robbie Gould', :team => 'CHI',:position => 'K')
  Player.create(:name => ' Nick Folk', :team => 'NYJ',:position => 'K')
  Player.create(:name => ' Adam Vinatieri', :team => 'IND',:position => 'K')
  Player.create(:name => ' Jay Feely', :team => 'ARI',:position => 'K')
  Player.create(:name => ' Mike Nugent', :team => 'CIN',:position => 'K')
  Player.create(:name => ' Dan Carpenter', :team => 'MIA',:position => 'K')
  Player.create(:name => ' John Kasay', :team => 'CAR',:position => 'K')
  Player.create(:name => ' Billy Cundiff', :team => 'BAL',:position => 'K')
  Player.create(:name => ' Matt Bryant', :team => 'ATL',:position => 'K')
  Player.create(:name => ' Joe Nedney', :team => 'SF',:position => 'K')
  Player.create(:name => ' Sebastian Janikowski', :team => 'OAK',:position => 'K')
  Player.create(:name => ' Graham Gano', :team => 'WAS',:position => 'K')
  Player.create(:name => ' Ryan Succop', :team => 'KC',:position => 'K')
  Player.create(:name => ' Josh Scobee', :team => 'JAC',:position => 'K')
  Player.create(:name => ' Jason Hanson', :team => 'DET',:position => 'K')
  Player.create(:name => ' Olindo Mare', :team => 'SEA',:position => 'K')
  Player.create(:name => ' Josh Brown', :team => 'STL',:position => 'K')
  Player.create(:name => ' Rian Lindell', :team => 'BUF',:position => 'K')
  Player.create(:name => ' Connor Barth', :team => 'TB',:position => 'K')
  Player.create(:name => ' Phil Dawson', :team => 'CLE',:position => 'K')
  Player.create(:name => ' Green Bay Packers', :team => 'GB',:position => 'DEF')
  Player.create(:name => ' Philadelphia Eagles', :team => 'PHI',:position => 'DEF')
  Player.create(:name => ' New Orleans Saints', :team => 'NO',:position => 'DEF')
  Player.create(:name => ' Minnesota Vikings', :team => 'MIN',:position => 'DEF')
  Player.create(:name => ' Pittsburgh Steelers', :team => 'PIT',:position => 'DEF')
  Player.create(:name => ' Baltimore Ravens', :team => 'BAL',:position => 'DEF')
  Player.create(:name => ' San Francisco 49ers', :team => 'SF',:position => 'DEF')
  Player.create(:name => ' Tennessee Titans', :team => 'TEN',:position => 'DEF')
  Player.create(:name => ' Cleveland Browns', :team => 'CLE',:position => 'DEF')
  Player.create(:name => ' New York Jets', :team => 'NYJ',:position => 'DEF')
  Player.create(:name => ' Dallas Cowboys', :team => 'DAL',:position => 'DEF')
  Player.create(:name => ' New England Patriots', :team => 'NE',:position => 'DEF')
  Player.create(:name => ' Indianapolis Colts', :team => 'IND',:position => 'DEF')
  Player.create(:name => ' Miami Dolphins', :team => 'MIA',:position => 'DEF')
  Player.create(:name => ' New York Giants', :team => 'NYG',:position => 'DEF')
  Player.create(:name => ' Denver Broncos', :team => 'DEN',:position => 'DEF')
  Player.create(:name => ' Chicago Bears', :team => 'CHI',:position => 'DEF')
  Player.create(:name => ' San Diego Chargers', :team => 'SD',:position => 'DEF')
  Player.create(:name => ' Atlanta Falcons', :team => 'ATL',:position => 'DEF')
  Player.create(:name => ' Buffalo Bills', :team => 'BUF',:position => 'DEF')
  Player.create(:name => ' Washington Redskins', :team => 'WAS',:position => 'DEF')
  Player.create(:name => ' Tampa Bay Buccaneers', :team => 'TB',:position => 'DEF')
  Player.create(:name => ' Cincinnati Bengals', :team => 'CIN',:position => 'DEF')
  Player.create(:name => ' Houston Texans', :team => 'HOU',:position => 'DEF')
  Player.create(:name => ' Carolina Panthers', :team => 'CAR',:position => 'DEF')
  Player.create(:name => ' Arizona Cardinals', :team => 'ARI',:position => 'DEF')
  Player.create(:name => ' Oakland Raiders', :team => 'OAK',:position => 'DEF')
  Player.create(:name => ' Seattle Seahawks', :team => 'SEA',:position => 'DEF')
  Player.create(:name => ' Kansas City Chiefs', :team => 'KC',:position => 'DEF')
  Player.create(:name => ' Detroit Lions', :team => 'DET',:position => 'DEF')
  Player.create(:name => ' Jacksonville Jaguars', :team => 'JAC',:position => 'DEF')
  Player.create(:name => ' St. Louis Rams', :team => 'STL',:position => 'DEF')
end