unless Poolie.exists?
  Poolie.create(:name => 'Chris Wise', :team_name => 'Wise-Asses', :draft_order => 1)
  Poolie.create(:name => 'Paul Wong', :team_name => 'The Real Super Dawgs', :draft_order => 2)
  Poolie.create(:name => 'Mike Peralta', :team_name => 'Fightin\' Filipinos', :draft_order => 3)
  Poolie.create(:name => 'Craig Kavanagh', :team_name => 'Craigbots', :draft_order => 4)
  Poolie.create(:name => 'Louis-Martin Parent', :team_name => 'Crackton United', :draft_order => 5)
  Poolie.create(:name => 'Chris Maloney', :team_name => 'Fancy Lions', :draft_order => 6)
  Poolie.create(:name => 'Jesse Fleming', :team_name => 'Big Poppa', :draft_order => 7)
  Poolie.create(:name => 'Dan Pascoli', :team_name => 'Camp Holdouts', :draft_order => 8)
  Poolie.create(:name => 'J-F Lagace', :team_name => 'Double Headed Jubins', :draft_order => 9)
  Poolie.create(:name => 'Fred Cooke', :team_name => 'The Godfather', :draft_order => 10)
  Poolie.create(:name => 'Marc Pascoli', :team_name => 'Stallions', :draft_order => 11)
  Poolie.create(:name => 'Dave Bisson', :team_name => 'Rub & Tuggers', :draft_order => 12)
end

unless Player.exists?(:position => 'DEF')
  Player.create(:position => 'DEF', :name => 'Arizona Cardinals ', :team => 'ARI')
  Player.create(:position => 'DEF', :name => 'Atlanta Falcons ', :team => 'ATL')
  Player.create(:position => 'DEF', :name => 'Baltimore Ravens ', :team => 'BAL')
  Player.create(:position => 'DEF', :name => 'Buffalo Bills ', :team => 'BUF')
  Player.create(:position => 'DEF', :name => 'Carolina Panthers ', :team => 'CAR')
  Player.create(:position => 'DEF', :name => 'Chicago Bears ', :team => 'CHI')
  Player.create(:position => 'DEF', :name => 'Cincinnati Bengals ', :team => 'CIN')
  Player.create(:position => 'DEF', :name => 'Cleveland Browns ', :team => 'CLE')
  Player.create(:position => 'DEF', :name => 'Dallas Cowboys ', :team => 'DAL')
  Player.create(:position => 'DEF', :name => 'Denver Broncos ', :team => 'DEN')
  Player.create(:position => 'DEF', :name => 'Detroit Lions ', :team => 'DET')
  Player.create(:position => 'DEF', :name => 'Green Bay Packers ', :team => 'GNB')
  Player.create(:position => 'DEF', :name => 'Houston Texans ', :team => 'HOU')
  Player.create(:position => 'DEF', :name => 'Indianapolis Colts ', :team => 'IND')
  Player.create(:position => 'DEF', :name => 'Jacksonville Jaguars ', :team => 'JAC')
  Player.create(:position => 'DEF', :name => 'Kansas City Chiefs ', :team => 'KAN')
  Player.create(:position => 'DEF', :name => 'Miami Dolphins ', :team => 'MIA')
  Player.create(:position => 'DEF', :name => 'Minnesota Vikings ', :team => 'MIN')
  Player.create(:position => 'DEF', :name => 'New England Patriots ', :team => 'NEW')
  Player.create(:position => 'DEF', :name => 'New Orleans Saints ', :team => 'NWO')
  Player.create(:position => 'DEF', :name => 'New York Giants ', :team => 'NYG')
  Player.create(:position => 'DEF', :name => 'New York Jets ', :team => 'NYJ')
  Player.create(:position => 'DEF', :name => 'Oakland Raiders ', :team => 'OAK')
  Player.create(:position => 'DEF', :name => 'Philadelphia Eagles ', :team => 'PHI')
  Player.create(:position => 'DEF', :name => 'Pittsburgh Steelers ', :team => 'PIT')
  Player.create(:position => 'DEF', :name => 'San Diego Chargers', :team => 'SDG')
  Player.create(:position => 'DEF', :name => 'San Francisco 49ers', :team => 'SFO')
  Player.create(:position => 'DEF', :name => 'Seattle Seahawks', :team => 'SEA')
  Player.create(:position => 'DEF', :name => 'St. Louis Rams', :team => 'STL')
  Player.create(:position => 'DEF', :name => 'Tampa Bay Buccaneers', :team => 'TAM')
  Player.create(:position => 'DEF', :name => 'Tennessee Titans', :team => 'TEN')
  Player.create(:position => 'DEF', :name => 'Washington Redskins', :team => 'WAS')
end